### ISSUE TITLE
Storage_read calls twice

### ISSUE THREAD

**Issue by hunjixin** [ontio/ontology-wasm-cdt-rust#43]
Storage_read calls twice. Is there any way to optimize this solution?

**Comment by laizy** [comment]
we must know the value size first to allocate the buffer to store that value, so we first allocate 32 bytes to read, for primitive value, such as `Address, H256, U256, u64` etc, the size will less than 32 bytes, so only one call is enough. but for other complex value , such as `Vec`, it need call twice. since the first read will be cached in contract execution context, so the second call will actually has little overhead cost.
how do you think? @hunjixin
